apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-harvesting
  labels:
    app: data-harvesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-harvesting
  template:
    metadata:
      labels:
        app: data-harvesting
    spec:
      containers:
        - name: data-harvesting
          image: uugai/data-harvesting:latest
          resources:
            limits:
              nvidia.com/gpu: 1 # requesting a single GPU
              nvidia.com/gpumem: 512 # Each vGPU contains 512m device memory
              cpu: 2
              memory: 2Gi
          env:
            # Project parameters
            - name: PROJECT_NAME
              value: "helmet"

            # Dataset parameters
            - name: DATASET_FORMAT
              value: "flat"
            - name: DATASET_VERSION
              value: "1"
            - name: DATASET_UPLOAD
              value: "True"

            # Forwarding
            - name: FORWARDING_MEDIA
              value: "False"
            - name: REMOVE_AFTER_PROCESSED
              value: "False"

            # Queue parameters
            - name: QUEUE_NAME
              value: "data-harvesting" # This is the topic of kafka we will read messages from.
            - name: QUEUE_HOST
              value: rabbitmq.rabbitmq:5672
            - name: QUEUE_EXCHANGE
            - name: QUEUE_USERNAME
              value: yourusername
            - name: QUEUE_PASSWORD
              value: yourpassword

            # Kerberos Vault parameters
            - name: STORAGE_URI
              value: "http://vault-lb.kerberos-vault/api"
            - name: STORAGE_ACCESS_KEY
              value: "52gyELgxutOXUWhF"
            - name: STORAGE_SECRET_KEY
              value: "k8DrcB@hQ5XfxDENzDKcnkxBHx"

            # Integration parameters
            - name: INTEGRATION_NAME
              value: "s3"

            # Roboflow parameters
            - name: RBF_API_KEY
              value: "YOUR KEY"
            - name: RBF_WORKSPACE
              value: "YOUR_WS"
            - name: RBF_PROJECT
              value: "YOUR_PROJ"
            
            # S3 parameters
            - name: S3_ENDPOINT
              value: "YOUR_ENDPOINT"
            - name: S3_ACCESS_KEY
              value: "YOUR_KEY"
            - name: S3_SECRET_KEY
              value: "YOUR_SECRET_KEY"
            - name: S3_BUCKET
              value: "YOUR_BUCKET"

            # Logging parameters
            - name: LOGGING
              value: "True"
            - name: TIME_VERBOSE
              value: "True"

            # Classification parameters
            - name: CLASSIFICATION_FPS
              value: "5"
            - name: CLASSIFICATION_THRESHOLD
              value: "0.25"
            - name: MAX_NUMBER_OF_PREDICTIONS
              value: "100"
            - name: FRAMES_SKIP_AFTER_DETECT
              value: "50"
            - name: MIN_DETECTIONS
              value: "1"
            - name: IOU
              value: "0.85"
